FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    django \
    djangorestframework \
    psycopg2-binary \
    python-dotenv \
    requests

COPY . .

EXPOSE 8000

CMD sh -c "gunicorn config.wsgi:application --bind 0.0.0.0:${PORT:-8000}"
