# Generated by Django 6.0.1 on 2026-01-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=3)),
                ('units', models.PositiveIntegerField(default=1)),
                ('patient_name', models.CharField(max_length=255)),
                ('hospital_name', models.CharField(max_length=255)),
                ('hospital_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('hospital_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('contact_phone', models.CharField(max_length=15)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SEARCHING_FOR_DONORS', 'Searching for Donors'), ('DONOR_ACCEPTED', 'Donor Accepted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='CREATED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
