# Generated by Django 6.0.1 on 2026-02-01 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='blood_component',
            field=models.CharField(blank=True, choices=[('WHOLE_BLOOD', 'Whole Blood'), ('PLATELETS', 'Platelets'), ('PLASMA', 'Plasma')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='case_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='requester_relation',
            field=models.CharField(choices=[('MYSELF', 'Myself'), ('FAMILY', 'Family Member'), ('FRIEND', 'Friend'), ('OTHER', 'Other')], default='MYSELF', max_length=20),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='required_by',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='urgency_level',
            field=models.CharField(choices=[('IMMEDIATE', 'Immediate (next few hours)'), ('TODAY', 'Today'), ('SCHEDULED', 'Scheduled')], default='IMMEDIATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='note',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['blood_group', 'city', 'status'], name='blood_reque_blood_g_98b3c9_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['urgency_level', 'created_at'], name='blood_reque_urgency_c59124_idx'),
        ),
    ]
