# Generated by Django 6.0.1 on 2026-02-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0003_alter_bloodrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='is_rare_blood',
            field=models.BooleanField(default=False),
        ),
    ]
