# Generated by Django 6.0.1 on 2026-02-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0005_bloodbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='urgency_level',
            field=models.CharField(choices=[('IMMEDIATE', 'Immediate (next few hours)'), ('TODAY', 'Today')], default='IMMEDIATE', max_length=20),
        ),
    ]
