# Generated by Django 6.0.1 on 2026-02-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0007_donationfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='is_assisted',
            field=models.BooleanField(default=False),
        ),
    ]
