# Generated by Django 6.0.1 on 2026-02-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0008_bloodrequest_is_assisted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'City Coverages',
            },
        ),
    ]
