# Generated by Django 6.0.1 on 2026-02-01 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_disable_on_accept', models.BooleanField(default=True)),
                ('auto_disable_after_donation', models.BooleanField(default=True)),
                ('notification_distance_km', models.IntegerField(choices=[(3, '3 km'), (5, '5 km'), (10, '10 km')], default=5)),
                ('emergency_types', models.CharField(choices=[('IMMEDIATE', 'Immediate Only'), ('ALL', 'All Urgent')], default='ALL', max_length=20)),
                ('push_notifications', models.BooleanField(default=True)),
                ('status_updates', models.BooleanField(default=True)),
                ('show_phone_number', models.BooleanField(default=False)),
                ('share_location', models.BooleanField(default=False)),
                ('language', models.CharField(default='en', max_length=10)),
                ('text_size', models.CharField(choices=[('NORMAL', 'Normal'), ('LARGE', 'Large')], default='NORMAL', max_length=10)),
                ('is_paused', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
