# Generated by Django 6.0.5 on 2026-06-23 06:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(max_length=10)),
                ('units', models.IntegerField(default=1)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('urgency_level', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('searching', 'Searching'), ('donor_accepted', 'Donor Accepted'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='searching', max_length=20)),
                ('escalation_phase', models.SmallIntegerField(default=1)),
                ('notified_count', models.IntegerField(default=0)),
                ('confirmed_count', models.IntegerField(default=0)),
                ('donor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('donor_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('requester_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blood_requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('is_donor', models.BooleanField(default=False)),
                ('is_available_donor', models.BooleanField(default=False)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('location', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('last_donation_date', models.DateTimeField(blank=True, null=True)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DonorResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('CONFIRMED', 'Confirmed'), ('ARRIVED', 'Arrived'), ('CANCELLED', 'Cancelled')], default='ACCEPTED', max_length=20)),
                ('distance_meters', models.FloatField(blank=True, null=True)),
                ('eta_minutes', models.IntegerField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'donor_responses',
                'managed': False,
            },
        ),
    ]
